spring:
  profiles:
    active: dev
  application:
    name: residential-hostel
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/residential_hostel
    username: root
    password: 111111
server:
  port: 8080
mybatis-plus:
  global-config:
    db-config:
        logic-delete-field: isDelete #??????0??????1????
        logic-delete-value: 1
        logic-not-delete-value: 0
        id-type: auto
#DataSource Config

#    mapper-locations: mapper/*.xml
#    global-config:
#      db-config:
#          logic-delete-field: isDelete #??????0??????1????
#          logic-delete-value: 1
#          logic-not-delete-value: 0
#          id-type: auto
